version: '3.7'

services:
  node:
      container_name: node_server
      build:
        context: .
        dockerfile: ./docker/Dockerfile
      ports:
       - 3000:3000
      volumes:
        - .:/app
      command: yarn dev
      networks:
        - common
      environment:
        PORT: 3000
        MONGO_URL: mongodb+srv://snag:712331@cluster0.gn0ez.mongodb.net/note_management?retryWrites=true&w=majority
        # MONGO_URL: mongodb://mongo/note_management
        NODE_ENV: 'development'

  mongo:
    container_name: mongo
    image : mongo
    ports:
     - 27017:27017
    volumes:
    - ./data:/data/db
    networks:
    - common
  nginx: 
    container_name: nginx
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d
    networks:
      - common
      
networks:
  common: